cd outfiles1 && root -l -q MiniTree1.C && ls *.root > out_files.txt
cd outfiles2 && root -l -q MiniTree2.C && ls *.root > out_files.txt
cd outfiles3 && root -l -q MiniTree3.C && ls *.root > out_files.txt
cd outfiles4 && root -l -q MiniTree4.C && ls *.root > out_files.txt
cd outfiles5 && root -l -q MiniTree5.C && ls *.root > out_files.txt
cd outfiles6 && root -l -q MiniTree6.C && ls *.root > out_files.txt
cd outfiles7 && root -l -q MiniTree7.C && ls *.root > out_files.txt
cd outfiles8 && root -l -q MiniTree8.C && ls *.root > out_files.txt
cd outfiles9 && root -l -q MiniTree9.C && ls *.root > out_files.txt
cd outfiles10 && root -l -q MiniTree10.C && ls *.root > out_files.txt
cd outfiles11 && root -l -q MiniTree11.C && ls *.root > out_files.txt
cd outfiles12 && root -l -q MiniTree12.C && ls *.root > out_files.txt
cd outfiles13 && root -l -q MiniTree13.C && ls *.root > out_files.txt
cd outfiles14 && root -l -q MiniTree14.C && ls *.root > out_files.txt
cd outfiles15 && root -l -q MiniTree15.C && ls *.root > out_files.txt
cd outfiles16 && root -l -q MiniTree16.C && ls *.root > out_files.txt
cd outfiles17 && root -l -q MiniTree17.C && ls *.root > out_files.txt
cd outfiles18 && root -l -q MiniTree18.C && ls *.root > out_files.txt
cd outfiles19 && root -l -q MiniTree19.C && ls *.root > out_files.txt
cd outfiles20 && root -l -q MiniTree20.C && ls *.root > out_files.txt
cd outfiles21 && root -l -q MiniTree21.C && ls *.root > out_files.txt
